# Generated by Django 3.0.7 on 2020-06-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0002_auto_20200609_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=4),
        ),
    ]
