# Generated by Django 3.0.7 on 2020-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0003_auto_20200609_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='electricity',
            field=models.IntegerField(default=0),
        ),
    ]
