# Generated by Django 3.0.7 on 2020-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0005_remove_room_electricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='electricity',
            field=models.IntegerField(default=0),
        ),
    ]
