# Generated by Django 3.0.7 on 2020-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0007_auto_20200609_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=4),
        ),
    ]
