# Generated by Django 3.0.7 on 2020-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0009_auto_20200609_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='door',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='motion',
            field=models.IntegerField(default=0),
        ),
    ]
