# Generated by Django 3.0.7 on 2020-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0010_auto_20200609_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
