# Generated by Django 3.0.7 on 2020-06-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cau', '0012_auto_20200610_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='electricity',
        ),
    ]
